apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-app
  labels:
    app: react-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-app
  template:
    metadata:
      labels:
        app: react-todo-app
    spec:
      containers:
        - name: react-todo-app
          image: github.io/mumby0168/rtodo/app
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: react-todo-app-service
  labels:
    app: react-todo-app-service
spec:
  selector:
    app: react-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-todo-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
     - rtodo.bemby.cloud
    secretName: ssl-cert-prod-rtodo

  rules:
  - host: rtodo.bemby.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-todo-app-service
            port:
              number: 80