apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-bemby-cloud-rtodo
  namespace: default
spec:
  secretName: ssl-cert-prod-rtodo
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rtodo.bemby.cloud
  dnsNames:
  - rtodo.bemby.cloud